### PR TITLE
feature: custom certificate support (#6)

### PR DESCRIPTION
**Pull request by HammerMeetNail**
* feature: custom certificate support

### CODE REVIEW

**Review by jonathankingfc — CHANGES_REQUESTED** [review]
One thing I would add here is a check that the provided SSL certs are valid for the Quay hostname.

**Comment by pbertera** [comment]
@jonathankingfc yes, seems a good idea, but I would then add another command switch to skip the check. I'm not sure that forcing the check is a good choice, for example someone may wants so use the IP address as Quay hostname but let the clients use the FQDN to connect to quay and use the FQDN into the certificate.

**Comment by jonathankingfc** [comment]
@pbertera i agree, that sounds like a plausible use case. and thank you for the contribution! it is much appreciated

**Comment by HammerMeetNail** [comment]
@pbertera Will you be able to get the new check and command switch in this week? Would love to get this merged before the holidays.

**Comment by pbertera** [comment]
@HammerMeetNail I think should be possible, I'll work on that on this and next evenings

**Comment by pbertera** [comment]
PR with the certificate check is #18

**Review by jonathankingfc — APPROVED** [review]
LGTM, just make sure to get https://github.com/quay/openshift-mirror-registry/pull/18 merged  as well.

**Comment by HammerMeetNail** [comment]
Merged #18 - waiting on CI to finish before resolving conflicts and merging this. https://github.com/quay/openshift-mirror-registry/actions/runs/1579309733

**Comment by HammerMeetNail** [comment]
I made a small change to skip `loadCerts` if none were presented. Will be rebasing and merging shortly.

**Comment by HammerMeetNail** [comment]
CI looks good: https://github.com/quay/openshift-mirror-registry/runs/4525135567?check_suite_focus=true

LGTM 👍

**Pull request merged**
