### PR TITLE
Update quayRoot location for remote install (PROJQUAY-3013)

### LINKED ISSUE #33: Installing airgapped fails when setting --quayRoot to non-default
I have downloaded offline tarball for release 1.0.0-RC2 from;
https://github.com/quay/openshift-mirror-registry/releases/download/1.0.0-RC2/openshift-mirror-registry-offline.tar.gz

Installation to a non-default **--quayRoot** location fails as follows;

```
sudo ./openshift-mirror-registry install --initPassword=passw0rd --targetHostname=installer.internal.net --ssh-key=/root/.ssh/id_rsa --quayRoot=/opt/registry/quay-install --sslCert=/home/ibmdemo/setup-quay-mirror-registry/mirror-registry.crt --sslKey=/home/ibmdemo/setup-quay-mirror-registry/mirror-registry.key --verbose

   __   __
  /  \ /  \     ______   _    _     __   __   __
 / /\ / /\ \   /  __  \ | |  | |   /  \  \ \ / /
/ /  / /  \ \  | |  | | | |  | |  / /\ \  \   /
\ \  \ \  / /  | |__| | | |__| | / ____ \  | |
 \ \/ \ \/ /   \_  ___/  \____/ /_/    \_\ |_|
  \__/ \__/      \ \__
                  \___\ by Red Hat
 Build, Store, and Distribute your Containers
	
INFO[2022-01-01 23:49:42] Install has begun                            
DEBU[2022-01-01 23:49:42] Ansible Execution Environment Image: quay.io/quay/openshift-mirror-registry-ee:latest 
DEBU[2022-01-01 23:49:42] Redis Image: registry.access.redhat.com/ubi8/pause:latest 
DEBU[2022-01-01 23:49:42] Quay Image: registry.redhat.io/quay/quay-rhel8:v3.6.1 
DEBU[2022-01-01 23:49:42] Redis Image: registry.redhat.io/rhel8/redis-6:1-25 
DEBU[2022-01-01 23:49:42] Postgres Image: registry.redhat.io/rhel8/postgresql-10:1-161 
INFO[2022-01-01 23:49:42] Found execution environment at /home/ibmdemo/setup-quay-mirror-registry/execution-environment.tar 
INFO[2022-01-01 23:49:42] Loading execution environment from execution-environment.tar 
DEBU[2022-01-01 23:49:42] Importing execution enviornment with command: /bin/bash -c sudo /usr/bin/podman image import \
					--change 'ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' \
					--change 'ENV HOME=/home/runner' \
					--change 'ENV container=oci' \
					--change 'ENTRYPOINT=["entrypoint"]' \
					--change 'WORKDIR=/runner' \
					--change 'EXPOSE=6379' \
					--change 'VOLUME=/runner' \
					--change 'CMD ["ansible-runner", "run", "/runner"]' \
					- quay.io/quay/openshift-mirror-registry-ee:latest < /home/ibmdemo/setup-quay-mirror-registry/execution-environment.tar 
Getting image source signatures
Copying blob 0ae606e5d5d2 skipped: already exists  
Copying config c852b7f2d0 done  
Writing manifest to image destination
Storing signatures
sha256:c852b7f2d05f6c3743b03363aab7f69653ba12fde2fa66f7dca9b01710f794d7
INFO[2022-01-01 23:49:45] Loading SSL certificate file /home/ibmdemo/setup-quay-mirror-registry/mirror-registry.crt 
INFO[2022-01-01 23:49:45] Loading SSL key file /home/ibmdemo/setup-quay-mirror-registry/mirror-registry.key 
INFO[2022-01-01 23:49:45] SSL certificate check succeeded              
INFO[2022-01-01 23:49:45] Attempting to set SELinux rules on /home/ibmdemo/setup-quay-mirror-registry/mirror-registry.crt 
chcon: can't apply partial context to unlabeled file '/home/ibmdemo/setup-quay-mirror-registry/mirror-registry.crt'
WARN[2022-01-01 23:49:45] Could not set SELinux rule. If your system does not have SELinux enabled, you may ignore this. 
INFO[2022-01-01 23:49:45] Attempting to set SELinux rules on /home/ibmdemo/setup-quay-mirror-registry/mirror-registry.key 
chcon: can't apply partial context to unlabeled file '/home/ibmdemo/setup-quay-mirror-registry/mirror-registry.key'
WARN[2022-01-01 23:49:45] Could not set SELinux rule. If your system does not have SELinux enabled, you may ignore this. 
INFO[2022-01-01 23:49:45] Found SSH key at /root/.ssh/id_rsa           
INFO[2022-01-01 23:49:45] Attempting to set SELinux rules on /root/.ssh/id_rsa 
chcon: can't apply partial context to unlabeled file '/root/.ssh/id_rsa'
WARN[2022-01-01 23:49:45] Could not set SELinux rule. If your system does not have SELinux enabled, you may ignore this. 
INFO[2022-01-01 23:49:45] Found image archive at /home/ibmdemo/setup-quay-mirror-registry/image-archive.tar 
INFO[2022-01-01 23:49:45] Attempting to set SELinux rules on image archive 
chcon: can't apply partial context to unlabeled file '/home/ibmdemo/setup-quay-mirror-registry/image-archive.tar'
WARN[2022-01-01 23:49:45] Could not set SELinux rule. If your system does not have SELinux enabled, you may ignore this. 
INFO[2022-01-01 23:49:45] Running install playbook. This may take some time. To see playbook output run the installer with -v (verbose) flag. 
DEBU[2022-01-01 23:49:45] Running command: sudo podman run --rm --interactive --tty --workdir /runner/project --net host -v /home/ibmdemo/setup-quay-mirror-registry/image-archive.tar:/runner/image-archive.tar -v /home/ibmdemo/setup-quay-mirror-registry/mirror-registry.crt:/runner/certs/quay.cert:Z -v /home/ibmdemo/setup-quay-mirror-registry/mirror-registry.key:/runner/certs/quay.key:Z -v /root/.ssh/id_rsa:/runner/env/ssh_key -e RUNNER_OMIT_EVENTS=False -e RUNNER_ONLY_FAILED_EVENTS=False -e ANSIBLE_HOST_KEY_CHECKING=False -e ANSIBLE_CONFIG=/runner/project/ansible.cfg --quiet --name ansible_runner_instance quay.io/quay/openshift-mirror-registry-ee ansible-playbook -i root@installer.internal.net, --private-key /runner/env/ssh_key -e "init_password=passw0rd quay_image=registry.redhat.io/quay/quay-rhel8:v3.6.1 redis_image=registry.redhat.io/rhel8/redis-6:1-25 postgres_image=registry.redhat.io/rhel8/postgresql-10:1-161 quay_hostname=installer.internal.net:8443 local_install=false quay_root=/opt/registry/quay-install" install_mirror_appliance.yml   

PLAY [Install Mirror Appliance] ***************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************
ok: [root@installer.internal.net]

TASK [mirror_appliance : Install Dependencies] ************************************************************************************************************************
included: /runner/project/roles/mirror_appliance/tasks/install-deps.yaml for root@installer.internal.net

TASK [mirror_appliance : Add IP address of all hosts to all hosts] ****************************************************************************************************
ok: [root@installer.internal.net]

TASK [mirror_appliance : Set SELinux Rules] ***************************************************************************************************************************
included: /runner/project/roles/mirror_appliance/tasks/set-selinux-rules.yaml for root@installer.internal.net

TASK [mirror_appliance : Set container_manage_cgroup flag on and keep it persistent across reboots] *******************************************************************
skipping: [root@installer.internal.net]

TASK [mirror_appliance : Create Podman Pod] ***************************************************************************************************************************
included: /runner/project/roles/mirror_appliance/tasks/create-podman-pod.yaml for root@installer.internal.net

TASK [mirror_appliance : Starting Pod with ports 80 and 443 exposed] **************************************************************************************************
changed: [root@installer.internal.net]

TASK [mirror_appliance : Autodetect Image Archive] ********************************************************************************************************************
included: /runner/project/roles/mirror_appliance/tasks/autodetect-image-archive.yaml for root@installer.internal.net

TASK [mirror_appliance : Checking for Image Archive] ******************************************************************************************************************
ok: [root@installer.internal.net -> localhost]

TASK [mirror_appliance : Create install directory for image-archive.tar dest] *****************************************************************************************
changed: [root@installer.internal.net]

TASK [mirror_appliance : Copy Images if /runner/image-archive.tar exists] *********************************************************************************************
changed: [root@installer.internal.net]

TASK [mirror_appliance : Unpack Images if /runner/image-archive.tar exists] *******************************************************************************************
changed: [root@installer.internal.net]

TASK [mirror_appliance : Loading Redis if redis.tar exists] ***********************************************************************************************************
fatal: [root@installer.internal.net]: FAILED! => {"changed": true, "cmd": "podman image import --change 'ENV PATH=/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' --change 'ENV container=oci'  --change 'ENV STI_SCRIPTS_URL=image:///usr/libexec/s2i' --change 'ENV STI_SCRIPTS_PATH=/usr/libexec/s2i' --change 'ENV APP_ROOT=/opt/app-root' --change 'ENV HOME=/var/lib/redis' --change 'ENV PLATFORM=el8' --change 'ENV REDIS_VERSION=6' --change 'ENV CONTAINER_SCRIPTS_PATH=/usr/share/container-scripts/redis' --change 'ENV REDIS_PREFIX=/usr' --change 'ENTRYPOINT=[\"container-entrypoint\"]' --change 'USER=1001' --change 'WORKDIR=/opt/app-root/src' --change 'EXPOSE=6379' --change 'VOLUME=/var/lib/redis/data' --change 'CMD [\"run-redis\"]' - registry.redhat.io/rhel8/redis-6:1-25 < /etc/quay-install/redis.tar", "delta": "0:00:00.003741", "end": "2022-01-01 23:51:45.598822", "msg": "non-zero return code", "rc": 1, "start": "2022-01-01 23:51:45.595081", "stderr": "/bin/sh: /etc/quay-install/redis.tar: No such file or directory", "stderr_lines": ["/bin/sh: /etc/quay-install/redis.tar: No such file or directory"], "stdout": "", "stdout_lines": []}

PLAY RECAP ************************************************************************************************************************************************************
root@installer.internal.net : ok=11   changed=4    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

ERRO[2022-01-01 23:51:45] An error occurred: exit status 2             
```

### PR DESCRIPTION
**Pull request by HammerMeetNail**
* Fixes #33
* Removes hardcoded quayRoot references
* Adds `--autoApprove` option
* Adds safety prompt for removing `quayRoot` on uninstall

Test Results:
```
[doconnor@omr-test-vm ~]$ ./openshift-mirror-registry install --targetUsername doconnor --targetHostname omr.demo.com --ssh-key ~/.ssh/id_ed25519 --initPassword password --quayHostname omr.demo.com --sslCert certs/ssl.cert --sslKey certs/ssl.key --quayRoot=/home/doconnor/quay --verbose

...

INFO[2022-01-05 19:20:31] Quay installed successfully, permament data are stored in /home/doconnor/quay

[doconnor@omr-test-vm ~]$ ll quay/
total 3421176
-rw-r--r--. 1 root root 1751644160 Jan  5 19:15 image-archive.tar
-rw-r--r--. 1 root root    3471360 Jan  5 13:50 pause.tar
drwxrwxr-x+ 3 root root         22 Jan  5 19:19 pg-data
-rw-r--r--. 1 root root  435077120 Jan  5 13:51 postgres.tar
drwxr-xr-x. 2 root root         56 Jan  5 19:19 quay-config
drwxrwxr-x+ 2 root root          6 Jan  5 19:19 quay-storage
-rw-r--r--. 1 root root 1040537600 Jan  5 13:51 quay.tar
-rw-r--r--. 1 root root  272547840 Jan  5 13:51 redis.tar
```

AutoApprove skip
```
[doconnor@omr-test-vm ~]$ ./openshift-mirror-registry uninstall --targetUsername doconnor --targetHostname omr.demo.com --ssh-key ~/.ssh/id_ed25519 --verbose

   __   __
  /  \ /  \     ______   _    _     __   __   __
 / /\ / /\ \   /  __  \ | |  | |   /  \  \ \ / /
/ /  / /  \ \  | |  | | | |  | |  / /\ \  \   /
\ \  \ \  / /  | |__| | | |__| | / ____ \  | |
 \ \/ \ \/ /   \_  ___/  \____/ /_/    \_\ |_|
  \__/ \__/      \ \__
                  \___\ by Red Hat
 Build, Store, and Distribute your Containers

INFO[2022-01-05 22:56:19] Uninstall has begun
Are you sure want to delete quayRoot directory /etc/quay-install? [y/n]
n
INFO[2022-01-05 22:56:25] Skipping deletion of quayRoot.
INFO[2022-01-05 22:56:25] Found execution environment at /home/doconnor/execution-environment.tar
INFO[2022-01-05 22:56:25] Loading execution environment from execution-environment.tar
DEBU[2022-01-05 22:56:25] Importing execution enviornment with command: /bin/bash -c sudo /usr/bin/podman image import \
					--change 'ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' \
					--change 'ENV HOME=/home/runner' \
					--change 'ENV container=oci' \
					--change 'ENTRYPOINT=["entrypoint"]' \
					--change 'WORKDIR=/runner' \
					--change 'EXPOSE=6379' \
					--change 'VOLUME=/runner' \
					--change 'CMD ["ansible-runner", "run", "/runner"]' \
					- quay.io/quay/openshift-mirror-registry-ee:latest < /home/doconnor/execution-environment.tar
Getting image source signatures
Copying blob 5f6f5c496e5e [--------------------------------------] 0.0b / 0.0b
Copying config 0f00d4dea7 done
Writing manifest to image destination
Storing signatures
sha256:0f00d4dea723253c4917777f9fa9e0efbd4b440d39e1ead2f7b000536cbcee5b
INFO[2022-01-05 22:56:28] Found SSH key at /home/doconnor/.ssh/id_ed25519
INFO[2022-01-05 22:56:28] Attempting to set SELinux rules on /home/doconnor/.ssh/id_ed25519
INFO[2022-01-05 22:56:28] Running uninstall playbook. This may take some time. To see playbook output run the installer with -v (verbose) flag.
DEBU[2022-01-05 22:56:28] Running command: sudo podman run --rm --interactive --tty --workdir /runner/project --net host  -v /home/doconnor/.ssh/id_ed25519:/runner/env/ssh_key -e RUNNER_OMIT_EVENTS=False -e RUNNER_ONLY_FAILED_EVENTS=False -e ANSIBLE_HOST_KEY_CHECKING=False -e ANSIBLE_CONFIG=/runner/project/ansible.cfg --quiet --name ansible_runner_instance quay.io/quay/openshift-mirror-registry-ee ansible-playbook -i doconnor@omr.demo.com, --private-key /runner/env/ssh_key uninstall_mirror_appliance.yml -e "quay_root=/etc/quay-install auto_approve=false"

PLAY [Uninstall Mirror Appliance] *************************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************************************
ok: [doconnor@omr.demo.com]

TASK [Delete Install Directory] ***************************************************************************************************************************************************************************************
skipping: [doconnor@omr.demo.com]
```

AutoApprove
```
[doconnor@omr-test-vm ~]$ ./openshift-mirror-registry uninstall --targetUsername doconnor --targetHostname omr.demo.com --ssh-key ~/.ssh/id_ed25519 --quayRoot=/home/doconnor/quay --verbose --autoApprove

   __   __
  /  \ /  \     ______   _    _     __   __   __
 / /\ / /\ \   /  __  \ | |  | |   /  \  \ \ / /
/ /  / /  \ \  | |  | | | |  | |  / /\ \  \   /
\ \  \ \  / /  | |__| | | |__| | / ____ \  | |
 \ \/ \ \/ /   \_  ___/  \____/ /_/    \_\ |_|
  \__/ \__/      \ \__
                  \___\ by Red Hat
 Build, Store, and Distribute your Containers

INFO[2022-01-05 22:54:07] Uninstall has begun
INFO[2022-01-05 22:54:07] Found execution environment at /home/doconnor/execution-environment.tar
INFO[2022-01-05 22:54:07] Loading execution environment from execution-environment.tar
DEBU[2022-01-05 22:54:07] Importing execution enviornment with command: /bin/bash -c sudo /usr/bin/podman image import \
					--change 'ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' \
					--change 'ENV HOME=/home/runner' \
					--change 'ENV container=oci' \
					--change 'ENTRYPOINT=["entrypoint"]' \
					--change 'WORKDIR=/runner' \
					--change 'EXPOSE=6379' \
					--change 'VOLUME=/runner' \
					--change 'CMD ["ansible-runner", "run", "/runner"]' \
					- quay.io/quay/openshift-mirror-registry-ee:latest < /home/doconnor/execution-environment.tar
Getting image source signatures
Copying blob 5f6f5c496e5e [--------------------------------------] 0.0b / 0.0b
Copying config 91a3f2a534 done
Writing manifest to image destination
Storing signatures
sha256:91a3f2a534e5a5bb5b484ac7328588a7771ff012ecb3c286a0b1e37995fe258b
INFO[2022-01-05 22:54:11] Found SSH key at /home/doconnor/.ssh/id_ed25519
INFO[2022-01-05 22:54:11] Attempting to set SELinux rules on /home/doconnor/.ssh/id_ed25519
INFO[2022-01-05 22:54:11] Running uninstall playbook. This may take some time. To see playbook output run the installer with -v (verbose) flag.
DEBU[2022-01-05 22:54:11] Running command: sudo podman run --rm --interactive --tty --workdir /runner/project --net host  -v /home/doconnor/.ssh/id_ed25519:/runner/env/ssh_key -e RUNNER_OMIT_EVENTS=False -e RUNNER_ONLY_FAILED_EVENTS=False -e ANSIBLE_HOST_KEY_CHECKING=False -e ANSIBLE_CONFIG=/runner/project/ansible.cfg --quiet --name ansible_runner_instance quay.io/quay/openshift-mirror-registry-ee ansible-playbook -i doconnor@omr.demo.com, --private-key /runner/env/ssh_key uninstall_mirror_appliance.yml -e "quay_root=/home/doconnor/quay auto_approve=true"

PLAY [Uninstall Mirror Appliance] *************************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************************************
ok: [doconnor@omr.demo.com]

TASK [Delete Install Directory] ***************************************************************************************************************************************************************************************
changed: [doconnor@omr.demo.com]
```

### CODE REVIEW

**Review by jonathankingfc — CHANGES_REQUESTED** [review]
Can we just add a check in uninstall.go make sure that --quayRoot is present before passing it to the ansible script? The ansible script just makes sure that the directory is absent, meaning that task will pass even if the directory was never there in the first place. This might lead to some confusion if a user forgets to pass a non-default --quayRoot flag but the uninstall passes successfully.

**Comment by HammerMeetNail** [comment]
Sure, I think I might also add a warning and/or prompt to make sure the user wants to delete the directory

**Comment by jonathankingfc** [comment]
If we do that, we should add a `--force` flag to the uninstall command. Additional prompts would cause conflicts with automation.

**Comment by HammerMeetNail** [comment]
@jonathankingfc Pushed up the changes. Opted for calling the flag `--autoApprove` instead. Ansible should only remove the directory if this value is set to true, either by passing the flag via cli or by entering `y` when prompted.

**Review by jonathankingfc — APPROVED** [review]
LGTM

**Pull request merged**
