### PR TITLE
feature: add --quayRoot option

### PR DESCRIPTION
**Pull request by pbertera**
This PR adds the `--quayRoot` option defining the folder where persistent data should be saved.
Adds also a small Makefile change to work with `ansible-runner` installed from pip

### CODE REVIEW

**Review by jonathankingfc — APPROVED** [review]
LGTM

**Review by jonathankingfc — CHANGES_REQUESTED** [review]
I believe you may need to rebase to get rid of merge conflicts. Otherwise LGTM

**Comment by pbertera** [comment]
Yes, I'll do in the next days. I'm also wondering if `--quayRoot` is a proper name, maybe better something like `--quayStorage` ?

**Comment by jonathankingfc** [comment]
@pbertera I think it should be more generic, since the root folder contains storage but also some config files. Either quayRoot or quayHome works fine.

**Comment by pbertera** [comment]
Unfortunately in the meantime I removed my fork and local branch. I created a new PR in #23
This can be closed

**Pull request closed without merging**
